import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'ali',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'zainal',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'shirts',
      images: '/images/tshirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'a comfort shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'shirts',
      images: '/images/tshirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'a cool shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'shirts',
      images: '/images/tshirt3.jpg',
      price: 60,
      brand: 'Raymond',
      rating: 4.0,
      numReviews: 8,
      countInStock: 20,
      description: 'a fit shirt',
    },
    {
      name: 'Hang Shirt',
      slug: 'hang-shirt',
      category: 'shirts',
      images: '/images/tshirt4.jpg',
      price: 100,
      brand: 'Puma',
      rating: 3.5,
      numReviews: 8,
      countInStock: 10,
      description: 'a coffe shirt',
    },
    {
      name: 'Free Tshirt',
      slug: 'free-tshirt',
      category: 'tshirts',
      images: '/images/tshirt5.jpg',
      price: 75,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'a comfort shirt',
    },
    {
      name: 'Fit TShirt',
      slug: 'fit-tshirt',
      category: 'tshirts',
      images: '/images/tshirt6.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 0,
      description: 'a huge shirt',
    },
  ],
};

export default data;
